let attackSrcX = 0
let attackSrcY = 0
const weapons = [
    stick = {
        minDamage:1,
        maxDamage:3,
        attackSpeed:1,
        attackRange:1,
        weight:2,
        damageSource:'blunt',
        attackType:'slash',
        dimensionX:1,
        dimensionY:3,
        name:'Stick',
        value:1,
        type:'weapon',
        knockback:15,
        imageSRC:'images/attack/stick.png'
        
    },
    dagger = {
        minDamage:3,
        maxDamage:3,
        attackSpeed:1.5,
        attackRange:0.5,
        weight:1,
        damageSource:'pierce',
        attackType:'slash',
        dimensionX:1,
        dimensionY:2,
        name:'Dagger',
        value:25,
        type:'weapon',
        knockback:10,
        imageSRC:'images/attack/dagger.png'
    },
    shortSword = {
        minDamage:3,
        maxDamage:5,
        attackSpeed:1.25,
        attackRange:0.75,
        weight:4,
        damageSource:'slash',
        attackType:'slash',
        dimensionX:1,
        dimensionY:3,
        name:'Short Sword',
        value:40,
        type:'weapon',
        knockback:15,
    },
    sword = {
        minDamage:5,
        maxDamage:9,
        attackSpeed:1,
        attackRange:1,
        weight:8,
        damageSource:'slash',
        attackType:'slash',
        dimensionX:1,
        dimensionY:3,
        name:'Sword',
        value:60,
        type:'weapon',
        knockback:18,
    },
    shortSpear = {
        minDamage:4,
        maxDamage:10,
        attackSpeed:0.8,
        attackRange:1.5,
        weight:10,
        damageSource:'pierce',
        attackType:'thrust',
        dimensionX:2,
        dimensionY:3,
        name:'Short Spear' ,
        value:75,
        type:'weapon',
        knockback:20,
        imageSRC:'images/attack/spear.png',
        
    },

]